services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wallance_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data