version: '3.1'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wallance_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data